### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by ghost** [juancarlospaco/unicodemoticon#18]
- Install Fails.
- Pypi was 500-ing on me when I uploaded.

```
$ sudo pip install --upgrade unicodemoticon
Collecting unicodemoticon
  Using cached unicodemoticon-2.2.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-a68dmrmu/unicodemoticon/setup.py", line 40, in <module>
        from unicodemoticon import (__author__, __url__, __email__, __license__,
      File "/tmp/pip-build-a68dmrmu/unicodemoticon/unicodemoticon/__init__.py", line 34, in <module>
        from .data import (CODES, STD_ICON_NAMES,
      File "/tmp/pip-build-a68dmrmu/unicodemoticon/unicodemoticon/data.py", line 9, in <module>
        'unicodemoticon.desktop')
      File "/usr/lib/python3.5/pkgutil.py", line 629, in get_data
        return loader.get_data(resource_name)
      File "<frozen importlib._bootstrap_external>", line 815, in get_data
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-a68dmrmu/unicodemoticon/unicodemoticon/unicodemoticon.desktop'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-a68dmrmu/unicodemoticon/

 15:49:40  ✘ 1  ~/code/unicodemoticon    master ✔ 
```

**Comment by ghost** [comment]
Fixed by https://github.com/juancarlospaco/unicodemoticon/commit/2111d5635f8048ff8d246164f1b474f9c7194342
